### ISSUE TITLE
cannot compile it

### ISSUE THREAD

**Issue by xzhoubayer** [wbieniec/copmem2#1]
CopMEM2.src/CopMEM2.cpp:1152:47: warning: attributes at the beginning of statement are ignored [-Wattributes]
  if (matches.size() < MATCH_BLOCK_SIZE[thID]) [[likely]]
                                               ^
CopMEM2.src/CopMEM2.cpp: In function ‘GenomeData readMultiFasta(std::__cxx11::string, char, bool, genometype)’:
CopMEM2.src/CopMEM2.cpp:1787:18: error: ‘replaceBadSymbols’ was not declared in this scope
   th[t] = thread(replaceBadSymbols, beg, end, badSymbols, paddingChar);
                  ^~~~~~~~~~~~~~~~~
CopMEM2.src/CopMEM2.cpp:1787:18: note: suggested alternative: ‘replaceBadSymbol’
   th[t] = thread(replaceBadSymbols, beg, end, badSymbols, paddingChar);
                  ^~~~~~~~~~~~~~~~~
                  replaceBadSymbol
CopMEM2.src/CopMEM2.cpp:1789:2: error: ‘replaceBadSymbols’ was not declared in this scope
  replaceBadSymbols(end, dst, badSymbols, paddingChar);
  ^~~~~~~~~~~~~~~~~
CopMEM2.src/CopMEM2.cpp:1789:2: note: suggested alternative: ‘replaceBadSymbol’
  replaceBadSymbols(end, dst, badSymbols, paddingChar);
  ^~~~~~~~~~~~~~~~~
  replaceBadSymbol
CopMEM2.src/CopMEM2.cpp: In function ‘SequenceVector2 readBlock(int, std::ifstream&, BlockItem&, char, bool)’:
CopMEM2.src/CopMEM2.cpp:1917:4: error: ‘replaceBadSymbols’ was not declared in this scope
    replaceBadSymbols(gen, dst, { 'a','c','g','t' }, paddingChar);
    ^~~~~~~~~~~~~~~~~
CopMEM2.src/CopMEM2.cpp:1917:4: note: suggested alternative: ‘replaceBadSymbol’
    replaceBadSymbols(gen, dst, { 'a','c','g','t' }, paddingChar);
    ^~~~~~~~~~~~~~~~~
    replaceBadSymbol
makefile:32: recipe for target 'copmem2' failed
make: *** [copmem2] Error 1

**Comment by wbieniec** [comment]
Missing declarations fixed. Thank you.

**Comment by wbieniec** [comment]
Fixed
